import { StyleSheet } from "react-native";

const baseShadow = {
  shadowColor: "#000",
  shadowOffset: { width: 0, height: 10 },
  shadowOpacity: 0.25,
  shadowRadius: 25,
  elevation: 20,
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#020617",
  },
  cameraShell: {
    flex: 1,
    backgroundColor: "#0f172a",
  },
  overlayContainer: {
    flex: 1,
    backgroundColor: "rgba(2, 6, 23, 0.45)",
    justifyContent: "space-between",
  },
  topControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 18,
  },
  headerMeta: {
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#f8fafc",
  },
  headerSubtitle: {
    fontSize: 12,
    color: "rgba(226, 232, 240, 0.76)",
    marginTop: 2,
  },
  topActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  statusContainer: {
    paddingHorizontal: 18,
    paddingTop: 12,
  },
  roundButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(15, 23, 42, 0.55)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.25)",
  },
  reticleWrapper: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  reticle: {
    width: 312,
    height: 312,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.28)",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(15, 23, 42, 0.18)",
    transform: [{ scale: 1 }],
  },
  corner: {
    position: "absolute",
    width: 40,
    height: 40,
    borderColor: "#22c55e",
  },
  topLeft: {
    top: 0,
    left: 0,
    borderLeftWidth: 4,
    borderTopWidth: 4,
    borderTopLeftRadius: 20,
  },
  topRight: {
    top: 0,
    right: 0,
    borderRightWidth: 4,
    borderTopWidth: 4,
    borderTopRightRadius: 20,
  },
  bottomLeft: {
    bottom: 0,
    left: 0,
    borderLeftWidth: 4,
    borderBottomWidth: 4,
    borderBottomLeftRadius: 20,
  },
  bottomRight: {
    bottom: 0,
    right: 0,
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderBottomRightRadius: 20,
  },
  gridLineHorizontal: {
    position: "absolute",
    left: 24,
    right: 24,
    height: 1,
    backgroundColor: "rgba(148, 163, 184, 0.22)",
    top: 104,
  },
  gridLineHorizontalSecondary: {
    top: undefined,
    bottom: 104,
  },
  gridLineVertical: {
    position: "absolute",
    top: 24,
    bottom: 24,
    width: 1,
    backgroundColor: "rgba(148, 163, 184, 0.22)",
    left: 104,
  },
  gridLineVerticalSecondary: {
    left: undefined,
    right: 104,
  },
  scanLine: {
    position: "absolute",
    left: 18,
    right: 18,
    height: 3,
    borderRadius: 2,
    backgroundColor: "rgba(56, 189, 248, 0.85)",
  },
  callout: {
    marginTop: 28,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 18,
    paddingVertical: 12,
    backgroundColor: "rgba(15, 23, 42, 0.7)",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.25)",
    gap: 10,
  },
  calloutText: {
    color: "#f8fafc",
    fontSize: 13,
    flexShrink: 1,
  },
  calloutSuccess: {
    backgroundColor: "rgba(45, 211, 111, 0.24)",
    borderColor: "rgba(45, 211, 111, 0.38)",
  },
  calloutDanger: {
    backgroundColor: "rgba(239, 68, 68, 0.22)",
    borderColor: "rgba(239, 68, 68, 0.42)",
  },
  calloutResultText: {
    fontWeight: "600",
  },
  boundingBoxContainer: {
    ...StyleSheet.absoluteFillObject,
  },
  boundingBox: {
    position: "absolute",
    borderWidth: 3,
    borderRadius: 18,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
  },
  boundingCornerBase: {
    position: "absolute",
    width: 22,
    height: 22,
    borderColor: "#f8fafc",
    borderStyle: "solid",
    opacity: 0.75,
  },
  boundingCornerTL: {
    top: -2,
    left: -2,
    borderTopWidth: 3,
    borderLeftWidth: 3,
    borderTopLeftRadius: 10,
  },
  boundingCornerTR: {
    top: -2,
    right: -2,
    borderTopWidth: 3,
    borderRightWidth: 3,
    borderTopRightRadius: 10,
  },
  boundingCornerBL: {
    bottom: -2,
    left: -2,
    borderBottomWidth: 3,
    borderLeftWidth: 3,
    borderBottomLeftRadius: 10,
  },
  boundingCornerBR: {
    bottom: -2,
    right: -2,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderBottomRightRadius: 10,
  },
  confidenceBadge: {
    position: "absolute",
    top: -32,
    left: 0,
    backgroundColor: "rgba(15, 23, 42, 0.92)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.25)",
  },
  confidenceBadgeText: {
    color: "#f8fafc",
    fontSize: 12,
    fontWeight: "600",
  },
  recycleFlag: {
    position: "absolute",
    left: 12,
    bottom: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    borderWidth: 1,
  },
  recycleFlagPositive: {
    backgroundColor: "rgba(45, 211, 111, 0.28)",
    borderColor: "rgba(45, 211, 111, 0.5)",
  },
  recycleFlagNegative: {
    backgroundColor: "rgba(239, 68, 68, 0.26)",
    borderColor: "rgba(239, 68, 68, 0.48)",
  },
  recycleFlagText: {
    color: "#f8fafc",
    fontSize: 12,
    fontWeight: "700",
  },
  modelBadge: {
    position: "absolute",
    bottom: -28,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(15, 23, 42, 0.75)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.25)",
  },
  modelBadgeText: {
    color: "#f8fafc",
    fontSize: 11,
    fontWeight: "600",
  },
  bottomOverlay: {
    paddingHorizontal: 18,
    paddingBottom: 24,
  },
  modelStatus: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "rgba(15, 23, 42, 0.7)",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.25)",
  },
  statusIconWrapper: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(56, 189, 248, 0.18)",
    alignItems: "center",
    justifyContent: "center",
  },
  statusTextContainer: {
    display:"flex",
    justifyContent:"flex-start",
    position:"relative",
  },
  statusTitle: {
    color: "#f8fafc",
    fontSize: 14,
    fontWeight: "600",
  },
  statusSubtitle: {
    color: "rgba(226, 232, 240, 0.76)",
    fontSize: 12,
    marginTop: 2,
  },
  impactTag: {
    marginTop: 12,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    backgroundColor: "rgba(34, 197, 94, 0.12)",
  },
  impactTagText: {
    color: "#22c55e",
    fontSize: 12,
    fontWeight: "600",
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(2, 6, 23, 0.78)",
    alignItems: "center",
    justifyContent: "center",
  },
  loadingCard: {
    width: 312,
    backgroundColor: "rgba(15, 23, 42, 0.92)",
    borderRadius: 22,
    paddingVertical: 28,
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.25)",
  },
  loadingTitle: {
    color: "#f8fafc",
    fontSize: 18,
    fontWeight: "700",
  },
  loadingText: {
    color: "rgba(226, 232, 240, 0.76)",
    fontSize: 13,
    textAlign: "center",
    paddingHorizontal: 28,
  },
  permissionCard: {
    flex: 1,
    margin: 24,
    borderRadius: 24,
    backgroundColor: "rgba(15, 23, 42, 0.92)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.25)",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    paddingHorizontal: 24,
  },
  permissionIconWrapper: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "rgba(34, 197, 94, 0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  permissionTitle: {
    color: "#f8fafc",
    fontSize: 20,
    fontWeight: "700",
  },
  permissionText: {
    color: "rgba(226, 232, 240, 0.76)",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
  },
  permissionButton: {
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#22c55e",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 16,
  },
  permissionButtonText: {
    color: "#f8fafc",
    fontSize: 14,
    fontWeight: "600",
  },
  resultSheet: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 34,
    backgroundColor: "#0f172a",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 24,
    borderWidth: 1,
    borderColor: "rgba(56, 189, 248, 0.3)",
    ...baseShadow,
  },
  resultContent: {
    gap: 18,
  },
  resultHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  resultPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
  },
  resultPillText: {
    fontSize: 13,
    fontWeight: "600",
  },
  secondaryButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: "rgba(148, 163, 184, 0.16)",
  },
  secondaryButtonText: {
    color: "rgba(226, 232, 240, 0.76)",
    fontSize: 12,
    fontWeight: "600",
  },
  resultTitle: {
    color: "#f8fafc",
    fontSize: 24,
    fontWeight: "700",
  },
  resultSubtitle: {
    color: "rgba(226, 232, 240, 0.76)",
    fontSize: 14,
  },
  metricsRow: {
    flexDirection: "row",
    gap: 12,
  },
  metricCard: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.6)",
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.25)",
  },
  metricLabel: {
    color: "rgba(226, 232, 240, 0.76)",
    fontSize: 12,
    marginBottom: 6,
  },
  metricValue: {
    color: "#f8fafc",
    fontSize: 15,
    fontWeight: "600",
  },
  instructionsCard: {
    backgroundColor: "rgba(15, 23, 42, 0.65)",
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.25)",
  },
  instructionsTitle: {
    color: "#f8fafc",
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 8,
  },
  instructionsText: {
    color: "rgba(226, 232, 240, 0.76)",
    fontSize: 13,
    lineHeight: 20,
  },
  storageRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(34, 197, 94, 0.12)",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  storageText: {
    color: "#22c55e",
    fontSize: 12,
    fontWeight: "600",
  },
  resultPlaceholder: {
    position: "absolute",
    alignItems: "center",
    gap: 10,
  },
  placeholderTitle: {
    color: "#f8fafc",
    fontSize: 18,
    fontWeight: "700",
  },
  placeholderText: {
    color: "rgba(226, 232, 240, 0.76)",
    fontSize: 13,
    textAlign: "center",
    lineHeight: 20,
  },
  captureBar: {
    position: "absolute",
    bottom: 24,
    left: 0,
    right: 0,
    paddingHorizontal: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  captureBarHidden: {
    opacity: 0,
    transform: [{ scale: 0.95 }],
  },
  utilityButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "rgba(15, 23, 42, 0.92)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.25)",
  },
  captureButton: {
    width: 92,
    height: 92,
    borderRadius: 46,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(34, 197, 94, 0.22)",
    borderWidth: 2,
    borderColor: "rgba(34, 197, 94, 0.4)",
  },
  captureButtonDisabled: {
    opacity: 0.6,
  },
  captureInner: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "#22c55e",
    alignItems: "center",
    justifyContent: "center",
  },
});